#!/usr/bin/env python

import ConfigParser
import optparse
import os.path

import freenav.flight
import freenav.freeview
import freenav.freecontrol

# Log file location
LOG_DIR = "/media/card/igc"

def main():
    parser = optparse.OptionParser()
    parser.add_option("-l", "--logdir", dest="logdir", default=LOG_DIR,
                      help="write IGC log file in DIR", metavar="DIR")
    parser.add_option("-w", "--window",
                      action="store_false", dest="fullscreen", default=True,
                      help="run application in window mode")
    (opts, args) = parser.parse_args()

    # Program configuration
    config = ConfigParser.ConfigParser()
    config.read(os.path.join(os.path.expanduser('~'), '.freeflight',
                             'freenav.ini'))

    # Get glider polar
    polar = {}
    for coeff in 'abc':
        polar[coeff] = config.getfloat('Polar', coeff)

    # Final glide safety height
    safety_height = config.getint('FinalGlide', 'safety_height')

    model = freenav.flight.Flight(polar, safety_height)
    view = freenav.freeview.FreeView(model, opts.fullscreen)
    controller = freenav.freecontrol.FreeControl(model, view, config)
    controller.main()

if __name__ == '__main__':
    main()
