#!/usr/bin/env python

import optparse

import freenav.flight
import freenav.freeview
import freenav.freecontrol

# Log file location
LOG_DIR = "/media/card/igc"

def main():
    parser = optparse.OptionParser()
    parser.add_option("-l", "--logdir", dest="logdir", default=LOG_DIR,
                      help="write IGC log file in DIR", metavar="DIR")
    parser.add_option("-w", "--window",
                      action="store_false", dest="fullscreen", default=True,
                      help="run application in window mode")
    (opts, args) = parser.parse_args()

    model = freenav.flight.Flight()
    view = freenav.freeview.FreeView(model, opts.fullscreen)
    controller = freenav.freecontrol.FreeControl(model, view)
    controller.main()

if __name__ == '__main__':
    main()
