#!/usr/bin/python2.5
import datetime

import gtk
import gobject

is_hildon_app = True
try:
    import hildon
except ImportError:
    is_hildon_app = False

import freenav.freedb
import freenav.tasklist

FT_TO_M = 0.3048

if is_hildon_app:
    AppBase = hildon.Program
else:
    AppBase = object

class QneApp(AppBase):
    def __init__(self):
        AppBase.__init__(self)

        self.db = freenav.freedb.Freedb()
        config = self.db.get_config()
        qne_date = datetime.date.fromtimestamp(config['qne_timestamp'])
        if (qne_date == datetime.date.today()):
            qne = int(round(self.db.get_config()['qne'] / FT_TO_M))
        else:
            qne = 0

        # Create window and add event handlers
        if is_hildon_app:
            self.window = hildon.Window()
        else:
            self.window = gtk.Window(gtk.WINDOW_TOPLEVEL)
        self.window.set_title('QNE')
        self.window.set_border_width(3)
        self.window.connect('key-press-event', self.on_keypress)
        self.window.connect('destroy', gtk.main_quit)
        self.window.connect('window-state-event', self.on_window_state_change)

        # Create QNE entry control
        label = gtk.Label('QNE (feet):')
        adjustment = gtk.Adjustment(qne, -1000, 2500, 1)
        self.spin_button = gtk.SpinButton(adjustment, climb_rate=0.5)
        hbox = gtk.HBox(False, 0)
        hbox.pack_start(label, False, True, 5)
        hbox.pack_start(self.spin_button, False, True, 5)

        alignment = gtk.Alignment(xalign=0.5)
        alignment.add(hbox)

        # Buttons
        button_box = gtk.HButtonBox()
        button_box.set_layout(gtk.BUTTONBOX_SPREAD)
        ok_button = gtk.Button("OK")
        ok_button.connect("clicked", self.on_ok_button)
        cancel_button = gtk.Button("Cancel")
        cancel_button.connect("clicked", self.on_cancel_button)
        clear_button = gtk.Button("Clear")
        clear_button.connect("clicked", self.on_clear_button)
        button_box.add(ok_button)
        button_box.add(cancel_button)
        button_box.add(clear_button)

        vbox = gtk.VBox(False, 0)
        vbox.pack_start(alignment, True, False, 10)
        vbox.pack_start(button_box, False, True, 10)
        self.window.add(vbox)

        self.window.show_all()

    def on_cancel_button(self, widget):
        """Cancel button pressed"""
        gtk.main_quit()

    def on_ok_button(self, widget):
        """OK button pressed"""
        self.db.set_qne(self.spin_button.get_value_as_int() * FT_TO_M)
        self.db.commit()
        gtk.main_quit()

    def on_clear_button(self, widget):
        """Clear button pressed"""
        self.db.clear_qne()
        self.db.commit()
        gtk.main_quit()

    def on_window_state_change(self, widget, event, *args):
        """Callback on window state change"""
        if event.new_window_state & gtk.gdk.WINDOW_STATE_FULLSCREEN:
            self.window_in_fullscreen = True
        else:
            self.window_in_fullscreen = False

    def on_keypress(self, widget, event, *args):
        """Callback on keypress"""
        if event.keyval == gtk.keysyms.F6:
            if self.window_in_fullscreen:
                self.window.unfullscreen()
            else:
                self.window.fullscreen()

    def run(self):
        self.window.show_all()
        gtk.main()

if __name__ == '__main__':
    qne_app = QneApp()
    qne_app.run()
