#!/usr/bin/env python

import ConfigParser
import logging
import os

import freenav.freedb
import freenav.taskedit

if __name__  == '__main__':
    # Program configuration
    config = ConfigParser.ConfigParser()
    config.read(os.path.join(os.path.expanduser('~'), '.freeflight',
                             'freenav.ini'))

    """handler = logging.StreamHandler()
    freelog = logging.getLogger('freelog')
    freelog.addHandler(handler)
    freelog.setLevel(logging.DEBUG)
    """

    db = freenav.freedb.Freedb()

    task_app = freenav.taskedit.TaskApp(db, config)
    task_app.run()
